[package]
edition = "2021"
name = "forward1"
version = "0.1.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
dotenv = "0.15.0"
tokio = {version = "1", features = ["full"]}
